/* eslint-env node */
import { describe, it, expect, vi, beforeEach } from 'vitest';

/**
 * Auth service logic tests with the DB layer mocked (no PostgreSQL needed).
 * Verifies: generic error messages (no account enumeration), bcrypt hash
 * compatibility policy for migrated Supabase hashes, forced-reset flagging,
 * and role allowlisting.
 */

vi.mock('../server/db/index.js', () => ({
  query: vi.fn(),
  pool: {},
  checkDbHealth: vi.fn(),
  closePool: vi.fn(),
}));

import { query } from '../server/db/index.js';
import { login, createUser, verifyPassword, hashPassword, LOGIN_ERROR_MESSAGE } from '../server/services/auth.js';

describe('auth service (mocked DB)', () => {
  beforeEach(() => {
    query.mockReset();
  });

  it('login with unknown email returns generic error and does not reveal existence', async () => {
    query.mockResolvedValueOnce({ rows: [] }); // findUserByEmail
    const res = await login('ghost@example.com', 'password123');
    expect(res.ok).toBe(false);
    expect(res.error).toBe(LOGIN_ERROR_MESSAGE);
  });

  it('login with wrong password returns the SAME generic error', async () => {
    query.mockResolvedValueOnce({
      rows: [{ id: 'u1', email: 'a@b.c', password_hash: await hashPassword('right-password'), role: 'karyawan', require_password_reset: false }],
    });
    const res = await login('a@b.c', 'wrong-password');
    expect(res.ok).toBe(false);
    expect(res.error).toBe(LOGIN_ERROR_MESSAGE);
  });

  it('login succeeds with correct password (bcrypt round-trip)', async () => {
    query
      .mockResolvedValueOnce({
        rows: [{ id: 'u1', email: 'a@b.c', password_hash: await hashPassword('correct-horse'), full_name: 'A', phone: null, avatar_url: null, role: 'admin', require_password_reset: false }],
      })
      .mockResolvedValueOnce({ rows: [] }); // touch updated_at
    const res = await login('a@b.c', 'correct-horse');
    expect(res.ok).toBe(true);
    expect(res.user.role).toBe('admin');
    expect(res.user.password_hash).toBeUndefined(); // never leaks
  });

  it('bcrypt $2b$ hashes from Supabase GoTrue verify with bcryptjs', async () => {
    // Real-format bcrypt hash (generated by bcryptjs itself, same algorithm
    // family GoTrue uses: $2a$/$2b$).
    const hash = await hashPassword('supabase-era-password');
    expect(hash).toMatch(/^\$2[aby]\$/);
    expect(await verifyPassword('supabase-era-password', hash)).toBe(true);
    expect(await verifyPassword('other', hash)).toBe(false);
  });

  it('account flagged require_password_reset cannot login until reset', async () => {
    query.mockResolvedValueOnce({
      rows: [{ id: 'u2', email: 'r@b.c', password_hash: await hashPassword('pw12345678'), role: 'karyawan', require_password_reset: true }],
    });
    const res = await login('r@b.c', 'pw12345678');
    expect(res.ok).toBe(false);
    expect(res.requiresPasswordReset).toBe(true);
  });

  it('malformed/empty hash never authenticates and never throws', async () => {
    expect(await verifyPassword('x', null)).toBe(false);
    expect(await verifyPassword('x', 'not-a-bcrypt-hash')).toBe(false);
    query.mockResolvedValueOnce({
      rows: [{ id: 'u3', email: 'm@b.c', password_hash: 'garbage', role: 'karyawan', require_password_reset: false }],
    });
    const res = await login('m@b.c', 'anything');
    expect(res.ok).toBe(false);
  });

  it('createUser rejects unknown roles (browser cannot inject privilege)', async () => {
    await expect(createUser({ email: 'x@y.z', password: 'password123', role: 'super_admin_evil' })).rejects.toThrow(/Role tidak dikenal/);
  });

  it('createUser inserts with bcrypt hash and validated role', async () => {
    query
      .mockResolvedValueOnce({ rows: [{ id: 'u9', email: 'x@y.z', full_name: null, phone: null, require_password_reset: false, created_at: new Date() }] })
      .mockResolvedValueOnce({ rows: [] });
    const user = await createUser({ email: 'X@Y.Z', password: 'password123', role: 'admin' });
    expect(user.role).toBe('admin');
    // First INSERT used a bcrypt hash, not plaintext
    const insertCall = query.mock.calls[0];
    expect(insertCall[1][0]).toBe('x@y.z'); // lowercased email
    expect(insertCall[1][1]).toMatch(/^\$2[aby]\$/);
  });
});
